`Course Instructor`: **John Chiasson**

`Author (TA)`: **Ruthvik Vaila**

# Notes
* We shall see the different modes of computation within `Tensorflow`.
* Read [more](https://www.tensorflow.org/guide/eager) about Eager mode. 
* In `TF2.0` eager mode is the default mode however in `<TF2.0` lazy mode is the default mode.
* Tested on `Python 3.7.5` with `Tensorflow 1.15.0` and `Keras 2.2.4`. 
* Tested on `Python 2.7.17` with `Tensorflow 1.15.3` and `Keras 2.2.4`.

# Lazy Mode

## Imports

In [1]:
import os, sys
sys.version

'3.7.5 (default, Nov  7 2019, 10:50:52) \n[GCC 8.3.0]'

In [2]:
import numpy as np
import tensorflow as tf
import IPython, keras
sess= tf.InteractiveSession()
from tensorflow.python.client import device_lib
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
run_metadata = tf.RunMetadata()
%load_ext tensorboard
config = tf.ConfigProto()
config.gpu_options.allow_growth=True
# this make sure thaat if using a gpu total gpu memory is not gobbled
# up by tensorflow and allows growth as required

Using TensorFlow backend.


In [3]:
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 3508486134850239660,
 name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 16301158018853506559
 physical_device_desc: "device: XLA_CPU device",
 name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 502816698747054689
 physical_device_desc: "device: XLA_GPU device",
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 7420175975
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 4548065032312345138
 physical_device_desc: "device: 0, name: GeForce RTX 2080 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5"]

In [4]:
tf.__version__

'1.15.0'

In [5]:
keras.__version__

'2.2.4'

## Setting up a computation graph

In [6]:
a_val = np.random.rand(2,2)
print("\n a_val is:\n{}".format(a_val))
b_val = np.random.rand(2,2)
print("\n b_val is: \n {}".format(b_val))


a = tf.Variable(initial_value=a_val, dtype=tf.float32, name='a')
print()
print(a)
b = tf.Variable(initial_value=b_val, dtype=tf.float32, name='b')
print(b)
add = tf.add(a,b,name='addition')
print(add)


 a_val is:
[[0.5338642  0.22223443]
 [0.54132684 0.33951193]]

 b_val is: 
 [[0.94638977 0.11635347]
 [0.58200272 0.46684294]]

<tf.Variable 'a:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'b:0' shape=(2, 2) dtype=float32_ref>
Tensor("addition:0", shape=(2, 2), dtype=float32)


* Notice that the `print` statement didn't really print anything because the variables `a` and `b` haven't been assigned any concrete values.

## Visualizing the above computation graph

* To run the Tensorboard `cd` into the `path` and then execute python -m tensorboard.main --logdir=./
* Tensorboard will be started as new tab in your default browser.

In [7]:
path = '/home/visionteam/tf_tutorials/logs/'
writer = tf.summary.FileWriter(path, sess.graph,flush_secs=1)
writer.flush()

In [9]:
%tensorboard --logdir {path}
# click on the `GRAPHS` tab in the below display

Reusing TensorBoard on port 6006 (pid 15295), started 0:02:44 ago. (Use '!kill 15295' to kill it.)

## Computing the graph using some constant values.

In [10]:
sess.run(add, feed_dict={a:a_val, b:b_val})

array([[1.4802539 , 0.33858788],
       [1.1233295 , 0.8063549 ]], dtype=float32)

# Restart the notebook to free up the `GPU` and `RAM`.

In [11]:
IPython.Application.instance().kernel.do_shutdown(True) #automatically restarts kernel

{'status': 'ok', 'restart': True}

# Eager Mode

## Imports

## Enabling Eager Mode

In [1]:
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

## Imports

In [2]:
import numpy as np
import IPython
sess= tf.InteractiveSession()
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
run_metadata = tf.RunMetadata()
%load_ext tensorboard
config = tf.ConfigProto()
config.gpu_options.allow_growth=True

## Computing in Eager mode

In [3]:
a_val = np.random.rand(2,2)
print("\n a_val is:\n{}".format(a_val))
b_val = np.random.rand(2,2)
print("\n b_val is: \n {}".format(b_val))


a = tf.Variable(initial_value=a_val, dtype=tf.float32, name='a')
print()
print(a)
b = tf.Variable(initial_value=b_val, dtype=tf.float32, name='b')
print(b)
add = tf.add(a,b,name='addition')
print(add)


 a_val is:
[[0.93857048 0.69912493]
 [0.15659762 0.037682  ]]

 b_val is: 
 [[0.06772153 0.895245  ]
 [0.70030068 0.79959559]]

<tf.Variable 'a:0' shape=(2, 2) dtype=float32, numpy=
array([[0.9385705 , 0.69912493],
       [0.15659761, 0.037682  ]], dtype=float32)>
<tf.Variable 'b:0' shape=(2, 2) dtype=float32, numpy=
array([[0.06772153, 0.895245  ],
       [0.7003007 , 0.7995956 ]], dtype=float32)>
tf.Tensor(
[[1.006292  1.5943699]
 [0.8568983 0.8372776]], shape=(2, 2), dtype=float32)


# Restart the notebook to free up the `GPU` and `RAM`.

In [ ]:
IPython.Application.instance().kernel.do_shutdown(True) #automatically restarts kernel